Page
taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment pull request #13
Opened 2023-06-08 07:28 UTC by taktak-0319

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-06-08 08:10 UTC, taktak-0319 commented
ローカルでは画像がちゃんと表示されているのですが、Github pages上だと画像が表示されないです。
(反映に時間がかかっているだけ？)
もし改善方法がわかれば
教えていただきたいです。

ローカルで開いた時↓
<img width="1440" alt="スクリーンショット 2023-06-08 17 07 43" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/c1d9593d-29ef-4ef9-8feb-809ee0cf2e50">


<img width="1440" alt="スクリーンショット 2023-06-08 17 07 47" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/c2b9975e-d4c8-4d23-a8a9-08d75f25852a">

<img width="1440" alt="スクリーンショット 2023-06-08 17 07 49" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/c938e980-3c55-4ced-834c-b1a6a432cf73">

2023-06-08 08:12 UTC, taktak-0319 commented
Github pages上↓
<img width="1440" alt="スクリーンショット 2023-06-08 17 04 13" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/09b5789d-42a9-4298-8924-acf9f2ae3ce5">
<img width="1440" alt="スクリーンショット 2023-06-08 17 04 19" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/d61178e8-7766-45eb-86fd-29152b449ebc">
<img width="1440" alt="スクリーンショット 2023-06-08 17 04 21" src="https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/124133847/79582f29-008b-4d63-8cd3-fc5ff95a246c">

2023-06-08 11:07 UTC, ssshun3 commented
画像が表示されない場合は以下のページを参考に修正してみてください。
[「ページを完成させる」で画像が表示されないとき](https://playground.wraptas.site/c8be28950297483ba8525455c2b3a80c)

2023-06-12 04:52 UTC, higashiji2000 requested changes
以下3点確認お願いします！

1
---
[お手本](https://demo.tcd-theme.com/tcd063/)と同様に、画面幅xl以上の場合topの背景とheaderを重ねてください。
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/28a7f2a9-2c6e-4165-a006-f61c25e3d2ce)


2
---
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/72be7ec0-c71c-406e-af1a-a05c1c435ccc)
画面幅が狭いときにcardsの縦方向の余白がなくなっているっぽいので、確認をお願いします。

3
---
![taktak-0319 github io_Takuma-Takahashi--frontend-basic-last-assignment_](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/a4fcd0e9-413a-4aa5-a901-d618be5963e2)
各コンポーネントの左右の余白が、`container-fluid` や `container-xxl` など統一されていないので、 `container` クラスに統一してください。
ただし、 news and events に関しては単に `container` クラスに直しただけだと背景の灰色も狭くなってしまうので、htmlの構造を少し変更する必要があります。
画像は検証ツール上で書き換えたスクリーンショットです。

2023-06-12 04:52 UTC, higashiji2000 commented on src/page/index.html
> +    <div class="container-fluid about">
```suggestion
    <div class="container about">
```

2023-06-12 04:52 UTC, higashiji2000 commented on src/page/index.html
> +    <div class="container-xxl news-and-events">
```suggestion
    <div class="news-and-events">
      <div class="container">
```
こんな感じで2つの要素に分割し、 `news-and-events` の方に背景色を設定してあげると、左右の余白はcontainer準拠で背景色は画面幅いっぱいに広がるという挙動が実現できるはずです。

2023-06-12 04:52 UTC, higashiji2000 commented on src/page/index.html
> +    <div class="plans container-lg">
```suggestion
    <div class="plans container">
```

2023-06-13 00:41 UTC, higashiji2000 approved these changes
LGTMです🍎

2023-06-13 01:42 UTC, merged