molecules/card
taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment pull request #3
Opened 2023-05-08 13:54 UTC by taktak-0319

## セルフチェック
- [x] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [x] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [x] 記述の重複はないか

2023-05-19 10:50 UTC, kogaokumura commented
transitionを効かせるところをlg以上のときにするのと、秒数を0.2から0.5に修正お願いします。

2023-05-21 04:58 UTC, higashiji2000 requested changes
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/0e772f9a-93c0-4e0e-bbfa-1b09df85ef74)

![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/cc67b937-fe42-454e-9c49-9bc2d160efe9)
上がstorybook、下がfigmaです。

- 画像の角が丸くなっている
- カード全体にボーダーがついている
こちら2点修正お願いします！

2023-05-21 04:58 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +        font-family: $fontfamily-gothic;
これはそれぞれの要素に対して指定しなくても大丈夫です！
(utilities.scssで設定しているため)

2023-05-21 06:22 UTC, higashiji2000 requested changes

2023-05-21 06:22 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +    }
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/c51fc88e-85c4-4ad5-9ddd-f200f21259cb)
```suggestion
    .card-body {
        padding: 32px;
        background-color: $white_smoke;
    }
```
背景色の追加だけお願いします！

2023-05-21 07:26 UTC, higashiji2000 approved these changes
LGTMです！

2023-05-21 07:28 UTC, merged