molecules/plan
taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment pull request #4
Opened 2023-05-18 08:12 UTC by taktak-0319

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-05-19 11:02 UTC, kogaokumura commented
planの場合、[table]タグではなく[ ul ]タグを使ったほうがいいと思います。
文字のフォントが違うのでその修正をお願いします。

2023-05-20 04:55 UTC, taktak-0319 commented
2度目のcommitでは`width`指定をしたのですが、現段階ではいらないようなので削除しました。

2023-05-21 06:36 UTC, higashiji2000 requested changes
いい感じです！

細かいですが「月額」は黒でお願いします。
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/2bcee3e8-232a-430e-aa54-275c30ee1ae7)

2023-05-21 06:36 UTC, higashiji2000 commented on src/components/molecules/plan/plan.scss
> +}
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/c1274a0b-a714-459e-8644-50951dc1112f)

この辺 `.plan` の入れ子にするようお願いします。
画像は[開発者ツール](https://www.notion.so/shinonome-inc/9bf1e0efdbbb4d7880e0d1c2dbb5e354?pvs=4)で `.plan` の外側に liを追加した例なのですが、このような無関係な `li` に対してもスタイルが当たってしまいます。

2023-05-21 06:36 UTC, higashiji2000 commented on src/components/molecules/plan/plan.scss
> +}
```suggestion
.plan {
    &:nth-child(even) {
        .list {
            box-sizing: border-box;
            border: solid 5px $orange_bistre;
            li:nth-child(1) {
                color: $white;
                background-color: $orange_bistre;
            }
        }
  }
}
```
&を使ってこういう書き方もできます。

2023-05-21 06:36 UTC, higashiji2000 commented on src/components/molecules/plan/plan.scss
> +    font-family: $fontfamily-gothic;
```suggestion
    text-align: center;
    overflow-wrap: break-word;
    font-size: $fontsize-s;
```
flexboxにしてしまうと、デフォルト値である`align-items: stretch;`によって中身が収縮してしまうので、ここではデフォルトの block要素のままで問題ないです。

参考：https://developer.mozilla.org/ja/docs/Web/CSS/align-items

2023-05-21 07:56 UTC, higashiji2000 requested changes
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/50291b8f-b2a4-4534-9733-6e5356b4953f)
横にすると高さがあってないので、修正お願いします。
borderのぶんpaddingの値を減らすのが適当かと思います！

2023-05-21 08:42 UTC, MoAI522 approved these changes
LGTM

2023-05-21 08:42 UTC, MoAI522 approved these changes
LGTM

2023-05-21 08:42 UTC, merged