organisms/news
taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment pull request #5
Opened 2023-05-19 09:13 UTC by taktak-0319

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-05-20 06:59 UTC, kogaokumura commented
hover時の色が変わるところをtext部分だけにする。
記事の部分にリンク機能を追加する。
news-and-events-titleの文字のサイズをsmallのとき小さくなるようにする。
以上3点の修正お願いします。

2023-05-21 05:49 UTC, higashiji2000 requested changes
3点修正お願いします

2023-05-21 05:49 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +    background-color: $white_smoke;
```suggestion
```

この段階では背景色は必要ないので削除しちゃって大丈夫です。

2023-05-21 05:49 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +                border: solid 1px $gray_gainsboro;
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/b68562f6-b483-43f7-aedf-95cb59cfd3de)

`.news-list` 同士のborderが隣り合って、2px の太さになってしまっています。
fimgaを見ると1pxの太さになっているので、修正をお願いします。

最初の要素以外の `border-top` を削除する、という実装になるかと思います。これを実現するためには、[擬似クラス](https://developer.mozilla.org/ja/docs/Web/CSS/Pseudo-classes)を使うとスマートにかけます。

2023-05-21 05:49 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +            text-decoration: none;
```suggestion
        .news-link {
            text-decoration: none;
                &:hover {
                    .info {
                        color: $orange_bistre;
                    }
              }
```
こうすると、クリックできる範囲とホバーで文字色が変わる範囲を一致させることができます。

2023-05-21 05:49 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +                    }
```suggestion
```
こっちは削除で！

2023-05-21 07:27 UTC, higashiji2000 approved these changes
LGTMです🔥

2023-05-21 07:29 UTC, merged