navbar作成
taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment pull request #6
Opened 2023-05-22 14:42 UTC by taktak-0319

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-05-31 11:51 UTC, ssshun3 commented
難しいパーツなのにとても完成度高くいいと思います！
ただ画面幅large以下のときのプラスアイコンのドロップダウンの挙動が気になりましたが1次レビューでは問題ないと思います👍

2023-05-31 14:54 UTC, higashiji2000 requested changes
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/818ff293-2e7b-491c-aa65-ab6186f74272)
xlのときのheightは90pxですが、現状それより大きくなっていそうです。

---

prettierが効いていないかもしれないので、確認お願いします。
prettierの設定については、[こちらのページの動画](https://shinonome-inc.notion.site/697a211574334d879cf467f0af501723)の5分あたりで説明しているので、忘れてたら参考にしてください。

---

lg以下のとき、現状conceptをクリックするとドロップダウンが開くと思います。
position: absolute等を利用してプラスボタンをconceptのセルとは別の要素として配置し、プラスボタンを押したときだけドロップダウンが開くようにできるとよりよいです。
（現状でも課題の段階では問題ないので、任意で修正お願いします。）

2023-06-01 14:10 UTC, higashiji2000 requested changes
![image](https://github.com/taktak-0319/Takuma-Takahashi--frontend-basic-last-assignment/assets/83479175/c14ca789-c77c-4a35-8afd-c02851f6dc89)
メニューが開いたときに隙間ができてしまっているので、修正お願いします。

2023-06-01 14:10 UTC, higashiji2000 commented
prettierは効いていそうか確認できたらコメントほしいです！

2023-06-01 19:58 UTC, taktak-0319 commented
変更を保存したら自動整形されるか、ということですかね？であればprettier 効いてると思います。

2023-06-06 05:27 UTC, higashiji2000 approved these changes

2023-06-06 05:36 UTC, merged